### ISSUE TITLE
Customized characteristics and Services not exposed

### ISSUE THREAD

**Issue by ranigupta1295** [tongo/ble-java#9]
We are configuring our services in the following way.
![image](https://user-images.githubusercontent.com/28503724/50392969-c8551580-0778-11e9-8728-fc0969123f41.png)

We are able to connect to the device through app but whatever services we are configuring is not being detected by the ble scanner app on my phone.
Ble scanner output is like 

![image](https://user-images.githubusercontent.com/28503724/50393071-b758d400-0779-11e9-93a5-1023e4372d72.png)

If you could share more information regarding how to configure Services and Characteristics, it would be a great help.

**Comment by vikram919** [comment]
Hi, can you share some information how this problem is resolved?
